# Generated by Django 3.1.4 on 2020-12-13 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201211_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
