# Generated by Django 3.1.4 on 2020-12-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_destination_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ('-date_posted',)},
        ),
    ]
